### PR TITLE
Improve user experience of pre-commit usage in PR validation

### PR DESCRIPTION
**Pull request by tpdownes**
- Use GitHub Actions to implement our pre-commit validation
  - web interface is cleaner and more likely to be known to new Toolkit contributors
  - caching improves speed of execution
- User can opt-in to automatic addition of commits that fix formatting issues discovered by PR

### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cloud HPC Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

### CODE REVIEW

**Comment by tpdownes** [comment]
See https://github.com/GoogleCloudPlatform/hpc-toolkit/actions/runs/7820241737/job/21334473558 for an example pre-commit GitHub Actions job.

**Comment by tpdownes** [comment]
@rohitramu does this action require extra configuration to block merge?

**Comment by rohitramu** [comment]
> @rohitramu does this action require extra configuration to block merge?

If I remember correctly, after the first time the check runs, we can set it as mandatory in the GitHub repo settings.

**Comment by rohitramu** [comment]
I was able to add the `pre-commit` GitHub Action as a mandatory check for the `develop` branch since it ran for this PR.

**Comment by tpdownes** [comment]
Thanks. I've disabled it as required for now, until we merge it onto develop.

**Comment by tpdownes** [comment]
Example of automatic fixing:

- [4th commit](https://github.com/tpdownes/hpc-toolkit/pull/40/commits)
- [GitHub Actions job](https://github.com/tpdownes/hpc-toolkit/actions/runs/7820806760/job/21336336145?pr=40)

**Review by rohitramu — APPROVED** [review]

**Pull request merged**
