### PR TITLE
Add slurm-gcp-v5-ubuntu2004 example to integration tests

### PR DESCRIPTION
**Pull request by heyealex**
Dependent on https://github.com/GoogleCloudPlatform/hpc-toolkit/pull/587 being merged. This will be rebased before submitting for review.

### Submission Checklist

* [x] Have you installed and run this change against pre-commit? (`pre-commit
  install`)
* [x] Are all tests passing? (`make tests`)
* [x] Have you written unit tests to cover this change?
* [x] Is unit test coverage still above 80%?
* [x] Have you updated all applicable documentation?
* [x] Have you followed the guidelines in our Contributing document?

### CODE REVIEW

**Review by cboneti — APPROVED** [review]
lgtm
q: why adding it to the same group as the other V5?

**Comment by heyealex** [comment]
Partially just because I could, and there was space to do so in that group, but also I like having a test that deploys 2 v5 clusters in the same group in parallel as a bit of a stress test. It seems to handle it pretty well actually!

**Review by tpdownes — CHANGES_REQUESTED** [review]
Unless there is a good reason not to, I believe that we should the [current published image family](https://github.com/SchedMD/slurm-gcp/blob/0abeab3f907778674aab7ffcfed5e48b9463ee3a/docs/images.md#published-image-family): `schedmd-v5-slurm-22-05-3-ubuntu-2004-lts`

**Comment by tpdownes** [comment]
> Partially just because I could, and there was space to do so in that group, but also I like having a test that deploys 2 v5 clusters in the same group in parallel as a bit of a stress test. It seems to handle it pretty well actually!

I think the problem with parallel builds is that a failure in one will cause the other to pause rather than cleanup. Group 3 and 4 are examples of doing it linearly for this reason.

**Comment by tpdownes** [comment]
It won't let me make a comment in an unchanged section, but line 20 of the integration group 3 YAML file should be updated to include the new test in whatever dependency order we decide upon.

**Comment by heyealex** [comment]
> Unless there is a good reason not to, I believe that we should the [current published image family](https://github.com/SchedMD/slurm-gcp/blob/0abeab3f907778674aab7ffcfed5e48b9463ee3a/docs/images.md#published-image-family): `schedmd-v5-slurm-22-05-3-ubuntu-2004-lts`

Fixed. I also ran another test, and it also fixed the issue with SMT core counts, so I reverted to using the default for `disable_smt` as well. Thanks for catching that!

**Comment by heyealex** [comment]
> > Partially just because I could, and there was space to do so in that group, but also I like having a test that deploys 2 v5 clusters in the same group in parallel as a bit of a stress test. It seems to handle it pretty well actually!
> 
> I think the problem with parallel builds is that a failure in one will cause the other to pause rather than cleanup. Group 3 and 4 are examples of doing it linearly for this reason.

Good point. I changed it to sequential, if it takes too much time I'll also move one of the tests to another group.

**Review by tpdownes — DISMISSED** [review]
Assuming the check passes, LGTM

**Comment by heyealex** [comment]
Switching to sequential execution did take longer, so I moved the ubuntu image to group 4 instead (both ran at around 30min before, now are ~50min). I will need a follow-up review when you have time.

**Review by cboneti — APPROVED** [review]

**Review by tpdownes — APPROVED** [review]

**Pull request merged**
