### PR TITLE
Add flux example to examples/README

### PR DESCRIPTION
**Pull request by mr0re1**

### CODE REVIEW

**Review by cboneti — CHANGES_REQUESTED** [review]
The links for both ramble and flux examples are broken.

**Comment by mr0re1** [comment]
No relative links in this README work ) I thinks it's GitHub commit browser limitation. It works in my VSCode though, and I guess it will work once change is committed.

**Comment by cboneti** [comment]
the markdown link format is different from vs code and github. To verify that the links are ok, one has to click here on "view file" and visualize it in GitHub. The last two links are still broken.

**Review by cboneti — APPROVED** [review]
Thanks!!

**Pull request merged**
