### PR TITLE
Update DDN EXAscaler to 6.2

### PR DESCRIPTION
**Pull request by rohitramu**

### CODE REVIEW

**Review by cboneti — APPROVED** [review]
Approved conditional to passing all integration tests that use Lustre.

**Comment by tpdownes** [comment]
@rohitramu I believe at least 3 of these tests that failed used Lustre

**Comment by rohitramu** [comment]
> @rohitramu I believe at least 3 of these tests that failed used Lustre

I was able to get past the errors by setting the default value of `node_count` to 1 instead of 0.  I'm not sure if this is the correct thing to do though, so I'd love to get your input on this.

**Comment by tpdownes** [comment]
It appears to me that this commit introduced a practical requirement that at least one `cls` instance be created because the replace_triggered_by argument includes it even count = 0.

https://github.com/DDNStorage/exascaler-cloud-terraform/commit/e33f439a0228f3a6df1c3fef7c0fbc580521a043

I think they meant to enforce >0 here, but did not:

```
  validation {
    condition     = var.cls.node_count >= 0
    error_message = "The cls.node_count value must be a positive."
  }

  validation {
    condition     = abs(var.cls.node_count) == var.cls.node_count
    error_message = "The cls.node_count value must be a positive."
  }

  validation {
    condition     = floor(var.cls.node_count) == ceil(var.cls.node_count)
    error_message = "The cls.node_count value must be an integer."
  }
}
```

Please merge this for now. Then create an issue in their repo that reports the following issues:

- their module incorrectly requires Terraform >= 1.0.0. The replace_triggered_by metaargument was introduced in 1.2.0
- the module no longer functions when Terraform variable var.cls.node_count is  0; is this intentional?
- if it is intentional, the validation blocks need to be modified. I believe the following is sufficient. The other blocks are 

``` 
  validation {
    condition     = var.cls.node_count > 0
    error_message = "The cls.node_count value must be a positive."
  }
```

**Comment by rohitramu** [comment]
> It appears to me that this commit introduced a practical requirement that at least one `cls` instance be created because the replace_triggered_by argument includes it even count = 0.
> 
> [DDNStorage/exascaler-cloud-terraform@e33f439](https://github.com/DDNStorage/exascaler-cloud-terraform/commit/e33f439a0228f3a6df1c3fef7c0fbc580521a043)
> 
> I think they meant to enforce >0 here, but did not:
> 
> ```
>   validation {
>     condition     = var.cls.node_count >= 0
>     error_message = "The cls.node_count value must be a positive."
>   }
> 
>   validation {
>     condition     = abs(var.cls.node_count) == var.cls.node_count
>     error_message = "The cls.node_count value must be a positive."
>   }
> 
>   validation {
>     condition     = floor(var.cls.node_count) == ceil(var.cls.node_count)
>     error_message = "The cls.node_count value must be an integer."
>   }
> }
> ```
> 
> Please merge this for now. Then create an issue in their repo that reports the following issues:
> 
> * their module incorrectly requires Terraform >= 1.0.0. The replace_triggered_by metaargument was introduced in 1.2.0
> * the module no longer functions when Terraform variable var.cls.node_count is  0; is this intentional?
> * if it is intentional, the validation blocks need to be modified. I believe the following is sufficient. The other blocks are not doing much.
> 
> ```
>   validation {
>     condition     = var.cls.node_count > 0
>     error_message = "The cls.node_count value must be a positive."
>   }
> ```

Thank you for the input Tom!  I've created an issue in the `exascaler-cloud-terraform` repo to report these issues: https://github.com/DDNStorage/exascaler-cloud-terraform/issues/17.  I will go ahead and merge this PR since all tests are now passing.

**Pull request merged**
