### PR TITLE
Update spack default version to v0.20.0

### PR DESCRIPTION
**Pull request by saltysoup**
### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cloud HPC Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

### CODE REVIEW

**Review by cboneti — APPROVED** [review]

**Review by cboneti — APPROVED** [review]

**Review by cboneti — COMMENTED** [review]
Hi Injae, 

You will likely need to update the readme as well, since the variable default changed. This is making the pre-commit validation fail. 

Cheers, 

Carlos

**Review by cboneti — CHANGES_REQUESTED** [review]
Hi Injae, 

The pre-commit is failing. If you run make tests, or pre-commit run, it will update the readme with the updated default value for the variable. Please add that file to this PR. :)

**Comment by tpdownes** [comment]
@cboneti the install is going more slowly due to 3 packages missing from our build cache:

```
==> No binary for gmake-4.4.1-3hd3wdu4sc7katjqurdilui2lcqljrbq found: installing from source
==> No binary for gawk-5.2.1-lpkzl36dadf3cih2so4ge5eoc7oaun5w found: installing from source
==> No binary for gcc-10.3.0-otwsigml4fmqgx2knpodi2nqw6jnbgbd found: installing from source
```

`gmake` is a new dependency introduced in Spack v0.20.0. This new dependency is, I think, the root cause of gcc-10.3.0 rebuilding. `gawk` was added in v0.18.0 but our build cache was literally created the day before v0.18.0. I reckon it was built off develop branch so it was identical to v0.18.0 dependencies. Somehow, though, `gawk` didn't make it into build cache. It only takes 19 seconds to build and we haven't noticed.

- https://github.com/spack/spack/blob/v0.20.0/var/spack/repos/builtin/packages/gcc/package.py
- https://github.com/spack/spack/blob/v0.19.0/var/spack/repos/builtin/packages/gcc/package.py

**Review by cboneti — APPROVED** [review]

**Pull request merged**
