### PR TITLE
Upgrade SchedMD community v5 modules to 5.5.0

### PR DESCRIPTION
**Pull request by SkylerMalinowski**
### Submission Checklist

* [ ] Have you installed and run this change against pre-commit? (`pre-commit
  install`)
* [ ] Are all tests passing? (`make tests`)
* [ ] Have you written unit tests to cover this change?
* [ ] Is unit test coverage still above 80%?
* [ ] Have you updated all applicable documentation?
* [ ] Have you followed the guidelines in our Contributing document?

### CODE REVIEW

**Review by tpdownes — CHANGES_REQUESTED** [review]
I am going to look harder at the integration test failures this week. In the meantime, @SkylerMalinowski, can you address the following 2 items:

1. Update the link to the requirements.txt file in the controller README to point to 5.5.0 tag?
2. Should google-cloud-secretmanager be in your requirements.txt file?

Re: 1. You might aggressively look for links to change with:

```
git grep 5.[0-9].[0-9] **/*schedmd*/*.{md,tf}
```

**Review by tpdownes — CHANGES_REQUESTED** [review]
I am actively testing why this fails our integration tests:

- re-running the automatic test
- manually deploying a blueprint and imitating the automatic test

I don't yet have an answer to that. In the meantime, please eliminate all remaining old links shown by this command (believe all are in README.md files):

```
git grep '5\.[0-9]\.[0-9]' **/*schedmd*/* | grep -v '5.5.0'
```

**Review by tpdownes — APPROVED** [review]
Approved, subject to build tests passing

**Comment by tpdownes** [comment]
One of the builds is failing again with the following error in the setup.log:

```
2023-03-01 23:12:19,580 ERROR: Error while getting metadata from http://metadata.google.internal/computeMetadata/v1/project/attributes/iov5ddcd0b-slurm-devel
2023-03-01 23:12:19,582 INFO: Setting up login
2023-03-01 23:12:19,587 INFO: installing custom scripts: login_mrntu4hz.d/ghpc_startup.sh
2023-03-01 23:12:19,588 DEBUG: install_custom_scripts: login_mrntu4hz.d/ghpc_startup.sh
2023-03-01 23:12:19,590 INFO: Set up network storage
2023-03-01 23:12:19,634 ERROR: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/slurm/scripts/setup.py", line 1173, in <module>
    main()
  File "/slurm/scripts/setup.py", line 1160, in main
    setup()
  File "/slurm/scripts/setup.py", line 1089, in setup_login
    setup_network_storage()
  File "/slurm/scripts/setup.py", line 653, in setup_network_storage
    ext_mounts, int_mounts = partition_mounts(all_mounts)
  File "/slurm/scripts/setup.py", line 644, in partition_mounts
    return separate(internal_mount, mounts)
  File "/slurm/scripts/util.py", line 677, in separate
    return reduce(lambda acc, el: acc[pred(el)].append(el) or acc, coll, ([], []))
  File "/slurm/scripts/util.py", line 677, in <lambda>
    return reduce(lambda acc, el: acc[pred(el)].append(el) or acc, coll, ([], []))
  File "/slurm/scripts/setup.py", line 641, in internal_mount
    mount_addr = socket.gethostbyname(mount.server_ip)
socket.gaierror: [Errno -2] Name or service not known
2023-03-01 23:12:19,635 ERROR: Aborting setup...
[tpdownes_google_com@iov5ddcd0b-login-mrntu4hz-001 ~]$ sudo cat /slurm/scripts/setup.log
2023-03-01 23:12:19,580 ERROR: Error while getting metadata from http://metadata.google.internal/computeMetadata/v1/project/attributes/iov5ddcd0b-slurm-devel
2023-03-01 23:12:19,582 INFO: Setting up login
2023-03-01 23:12:19,587 INFO: installing custom scripts: login_mrntu4hz.d/ghpc_startup.sh
2023-03-01 23:12:19,588 DEBUG: install_custom_scripts: login_mrntu4hz.d/ghpc_startup.sh
2023-03-01 23:12:19,590 INFO: Set up network storage
2023-03-01 23:12:19,634 ERROR: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/slurm/scripts/setup.py", line 1173, in <module>
    main()
  File "/slurm/scripts/setup.py", line 1160, in main
    setup()
  File "/slurm/scripts/setup.py", line 1089, in setup_login
    setup_network_storage()
  File "/slurm/scripts/setup.py", line 653, in setup_network_storage
    ext_mounts, int_mounts = partition_mounts(all_mounts)
  File "/slurm/scripts/setup.py", line 644, in partition_mounts
    return separate(internal_mount, mounts)
  File "/slurm/scripts/util.py", line 677, in separate
    return reduce(lambda acc, el: acc[pred(el)].append(el) or acc, coll, ([], []))
  File "/slurm/scripts/util.py", line 677, in <lambda>
    return reduce(lambda acc, el: acc[pred(el)].append(el) or acc, coll, ([], []))
  File "/slurm/scripts/setup.py", line 641, in internal_mount
    mount_addr = socket.gethostbyname(mount.server_ip)
socket.gaierror: [Errno -2] Name or service not known
2023-03-01 23:12:19,635 ERROR: Aborting setup...
```

We'll investigate whether it's related to problem solved by #967. I may rebase this PR off a develop branch. The ball is in my court for now.

**Comment by tpdownes** [comment]
A rebase and submission of builds 1,2,4,5 still yielded one instance of the wait-for-munge problem, presumably with setup.log similar to above. I will investigate more.

**Comment by tpdownes** [comment]
The failure is being triggered by the change from commit https://github.com/SchedMD/slurm-gcp/commit/d4822eb61240cf5e84aafbd89b1660f0c0b8d94d. In the `network_storage` block output by the DDN-exascaler module, the server_ip field is in the format `10.0.0.5@tcp` rather than being a pure IP address or DNS-resolvable name.

This is probably bad, but I also want to discuss with the Toolkit team whether we believe the commit above addresses the issue (internal no. 294) we reported.

**Comment by tpdownes** [comment]
Examining the mounting code in scripts/setup.py, it looks like the field `server_ip` has and continues to be treated as "anything to the left of :" in an fstab entry (e.g. an IP address, resolvable DNS-name). We therefore believe the code should continue to respect that and that it should continue to function specifically for Lustre fstab entries.

In the specific case of Lustre, it's common for `@tcp` to be included and there can also be multiple hosts separated by colons specified: 

https://wiki.lustre.org/Mounting_a_Lustre_File_System_on_Client_Nodes

We are not advising changing the name of the field from server_ip.

**Comment by SkylerMalinowski** [comment]
Because this is a script issue on our end, we will have to fix this and submit another PR/MR for our next release (5.5.1 or 5.6.0).

Thanks @tpdownes !

**Pull request closed without merging**
