### PR TITLE
Output better executable path

### PR DESCRIPTION
**Pull request by mr0re1**

### CODE REVIEW

**Review by tpdownes — CHANGES_REQUESTED** [review]
In addition to the necessary golden copy changes, please:

1. call [filepath.Clean](https://pkg.go.dev/path/filepath#Clean) on the result to avoid output below
2. nit: consider [filepath.Rel](https://pkg.go.dev/path/filepath#Rel) to shorten the output when possible

```
 ~/projects/../projects/hpc/hpc-toolkit/ghpc create community/examples/hpc-slurm-ubuntu2004.yaml
To deploy your infrastructure please run:

/Users/tpdownes/projects/../projects/hpc/hpc-toolkit/ghpc deploy slurm-gcp-v5

Find instructions for cleanly destroying infrastructure and advanced manual
deployment instructions at:

slurm-gcp-v5/instructions.txt
```

**Comment by tpdownes** [comment]
> 2. nit: consider [filepath.Rel](https://pkg.go.dev/path/filepath#Rel) to shorten the output when possible

This would be bad if the output begins with `..`. Don't overthink this, but take a look if there's something easy to do here that avoids super long strings.

**Comment by mr0re1** [comment]
Addressed.
```sh
$ ../hpc-toolkit/ghpc create tst.yaml -w
$ ~/wp/../wp/./hpc-toolkit/ghpc create tst.yaml -w
...
./ghpc deploy tst
```

**Review by tpdownes — CHANGES_REQUESTED** [review]
I think my suggestion / new implementation broke something along the way. I have ~/bin in my PATH and I am executing that, but now it's picking up `ghpc` from my CWD.

```
~/p/h/hpc-toolkit (this_path)❯❯❯ which ghpc
/Users/tpdownes/bin/ghpc
~/p/h/hpc-toolkit (this_path)❯❯❯ ghpc create -w -l ERROR --vars project_id=toolkit-demo-zero-e913 examples/hpc-enterprise-slurm.yaml
To deploy your infrastructure please run:

./ghpc deploy hpc01

Find instructions for cleanly destroying infrastructure and advanced manual
deployment instructions at:

hpc01/instructions.txt
~/p/h/hpc-toolkit (this_path)❯❯❯ rm -f ghpc
~/p/h/hpc-toolkit (this_path)❯❯❯ ghpc create -w -l ERROR --vars project_id=toolkit-demo-zero-e913 examples/hpc-enterprise-slurm.yaml
To deploy your infrastructure please run:

ghpc deploy hpc01

Find instructions for cleanly destroying infrastructure and advanced manual
deployment instructions at:

hpc01/instructions.txt
```

My simple thought was "run filepath.Clean on the output of algorithm".

**Comment by tpdownes** [comment]
> My simple thought was "run filepath.Clean on the output of algorithm".

Maybe as simple as

```
  cleanArgs0 := filepath.Clean(args0)
```

and return that.

**Comment by mr0re1** [comment]
>  I have ~/bin in my PATH and I am executing that, but now it's picking up ghpc from my CWD.

Yeah, because `args0 == ghpc`, attempt to clean it up makes `args0 == ./ghpc`, `./ghpc` is not the same file as `ghpc from PATH` => output `args0 (./ghpc)`. 
Updated.

**Review by tpdownes — APPROVED** [review]
I'm not sure I ultimately like the potential for `../` in beginning of command but this is a huge improvement over status quo and cleanly detects any use of GHPC from the path and cwd.

**Pull request merged**
