### PR TITLE
Do not chmod spack installation unless user specifies mode

### PR DESCRIPTION
**Pull request by nick-stroud**
Use built in spack configuration to grant group write permissions. Do not chmod spack install unless user specifies a mode.

### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cloud HPC Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

### CODE REVIEW

**Review by douglasjacobsen — APPROVED** [review]

**Review by danielahlin — APPROVED** [review]
Looks good. I'm no ansible expert - I assume you've checked that "null" means nothing changes - right?

**Comment by nick-stroud** [comment]
`I assume you've checked that "null" means nothing changes` > I did confirm this but it is really only true in the case that the script is being run as root. Although that is our case, I figured it is just safer to not run that task unless user has provided some input. I have pushed an update in a second commit.

**Review by tpdownes — APPROVED** [review]
I'm not convinced that the 2nd commit is really all that helpful, but I'll defer to your judgement as it was discussed.

**Comment by nick-stroud** [comment]
The documentation for `ansible.builtin.file` says things like _ When left unspecified, it uses the current user unless you are root, in which case it can preserve the previous ownership._. My interpretation is that when run as root (as we do) this task will have no effect. If the script were to be run as a user with all inputs null, it would have an effect of changing permissions to that user/group. While this does not affect us in our normal use case, I didn't like having potential side effects when the user's intent was clearly to take no action.

**Pull request merged**
