### PR TITLE
Update SchedMD modules to 5.6.3 (from 5.6.2)

### PR DESCRIPTION
**Pull request by SkylerMalinowski**
### Submission Checklist

* [x] Have you installed and run this change against pre-commit? (`pre-commit
  install`)
* [x] Are all tests passing? (`make tests`)
* [ ] Have you written unit tests to cover this change?
* [x] Is unit test coverage still above 80%?
* [x] Have you updated all applicable documentation?
* [x] Have you followed the guidelines in our Contributing document?

### CODE REVIEW

**Review by cboneti — CHANGES_REQUESTED** [review]
Shouldn't the controller expose its newly added output? (https://github.com/SchedMD/slurm-gcp/commit/be610be8c4b459fbe8be32f968997f914ab874be#diff-204625a3602feb0099fa10345ddb53424263341577cc43fd51ffef6ebfe66d0c).

**Comment by SkylerMalinowski** [comment]
Exposing it on the controller would make it available for toolkit to use. For this PR there is nothing that can be done as the requested change would have to be released in a subsequent version.

**Review by cboneti — APPROVED** [review]

**Comment by cboneti** [comment]
Ok, I will merge it as is while the outputs are not available at the controller.

**Pull request merged**
