### PR TITLE
Default scope now allows reading AND writing.

### PR DESCRIPTION
**Pull request by sandwichmaker**
Previously the scope for the vm only allowed it to read from GCS. Now both read and writes are allowed.

### Submission Checklist

I have used this change in practice on a cluster of my own. Make tests seem to fail with a build problem on my mac with a complaint about missing nproc.

```
*********** running basic integration tests ***********
tools/validate_configs/validate_configs.sh
tools/validate_configs/validate_configs.sh: line 105: nproc: command not found
make: *** [validate_configs] Error 127
```

### CODE REVIEW

**Comment by nick-stroud** [comment]
Just FYI @sandwichmaker, I took a few actions:
1. I switched the target branch to `develop`. Once merged it will only be accessible on the `develop` branch for some time until it makes it into an official release.
2. The failing pr-validation appeared to be from a tflint issue that had already been fixed on `develop`. I merged the latest changes in from `develop` and am re-running tests.

**Review by nick-stroud — APPROVED** [review]

**Comment by nick-stroud** [comment]
So the merged cleared the tflint error but there is still legitimate `terraform-readme` error that needs to be addressed.

**Comment by sandwichmaker** [comment]
Let me take a look in the morning. This is my first time doing this on GitHub.

**Comment by nick-stroud** [comment]
I do not get a pre-commit error from `go-mod-tidy` where @sandwichmaker is seeing the error (8da491b258633877102af41aa66bc001d5efa9ec) but neither do I get any complaint from the head of this branch. Since pr-validation also did not complain about the current state, I feel comfortable merging as is.

**Review by nick-stroud — APPROVED** [review]

**Pull request merged**
