### PR TITLE
Slurm-gcp v5 modules

### PR DESCRIPTION
**Pull request by heyealex**
NOTE: This PR is being broken into smaller components to be reviewed separately. This PR will stay open as a draft to provide context for reviewers. 

New modules have been added that support [slurm-gcp](https://github.com/SchedMD/slurm-gcp/tree/v5.0.2) v5 to the level that is supported currently in the v4 slurm-gcp modules. An example has been added to the community examples showing how it can be used in a similar way to the v4 slurm-gcp modules that are currently the default in most core examples.

### Submission Checklist

* [x] Have you installed and run this change against pre-commit? (`pre-commit
  install`)
* [x] Are all tests passing? (`make tests`)
* [x] Have you written unit tests to cover this change?
* [x] Is unit test coverage still above 80%?
* [x] Have you updated all applicable documentation?
* [x] Have you followed the guidelines in our Contributing document?

### CODE REVIEW

**Review by cboneti — COMMENTED** [review]
It generally looks ok to me, but I did not review all the files in detail. 
Questions: 
1) Instead of having a V5 example, when should we not have a V4 example and move all other examples to V5?
2) When should we put a 6 months deprecation notice in all the V4 READMEs and examples?
3) Did we create a task to upgrade V4 to the lasted version on the branch?

**Comment by tpdownes** [comment]
@cboneti I submitted #356 a while back. I've been looking forward to its official release alongside updates to the VPC module.

**Comment by cboneti** [comment]
> @cboneti I submitted #356 a while back. I've been looking forward to its official release alongside updates to the VPC module.

You are right. I thought there was a newer version on the 4.x branch. Thanks!

**Comment by heyealex** [comment]
Closing as all of this content has been merged or is soon to be in review.

**Pull request closed without merging**
