### PR TITLE
Remove blueprint_dir update in integration tests

### PR DESCRIPTION
**Pull request by heyealex**
The blueprint_name is not used anywhere now that deployment_name is used for the directory location, this PR removes the update and any other references to the variable.

### Submission Checklist

* [x] Have you installed and run this change against pre-commit? (`pre-commit
  install`)
* [x] Are all tests passing? (`make tests`)
* [x] Have you written unit tests to cover this change?
* [x] Is unit test coverage still above 80%?
* [x] Have you updated all applicable documentation?
* [x] Have you followed the guidelines in our Contributing document?

### CODE REVIEW

**Comment by heyealex** [comment]
I will run integration tests before submitting, this is lower priority than [other PRs](https://github.com/GoogleCloudPlatform/hpc-toolkit/pull/581), so I'm going to wait until they are passing or merged in.

**Review by cboneti — DISMISSED** [review]

**Comment by tpdownes** [comment]
I have assigned #583 to @heyealex which is somewhat likely to cause an easily resolved conflict with this PR.

**Comment by heyealex** [comment]
> I have assigned #583 to @heyealex which is somewhat likely to cause an easily resolved conflict with this PR.

Merge yours first, this is lower priority, and I can handle the conflict here.

**Comment by heyealex** [comment]
I had to dismiss the prior approval to handle the conflict

**Review by cboneti — APPROVED** [review]

**Pull request merged**
