### PR TITLE
Slurm GCP version update; will cooldown before deleting orphan nodes

### PR DESCRIPTION
**Pull request by nick-stroud**
### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cloud HPC Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

### CODE REVIEW

**Comment by nick-stroud** [comment]
Integration test has run 3 times. 2 passed, 1 stockout on c2d partition after running n2 and c2 partitions. This failure is past where the problem occurs. So I consider this passing 3 times.

**Comment by nick-stroud** [comment]
Waiting for approval of https://github.com/GoogleCloudPlatform/slurm-gcp/pull/54.

**Review by tpdownes — CHANGES_REQUESTED** [review]
I suggest that you run

```
git sed '5\.10\.4' '5.10.5' -- **/*.md
```

to eliminate remaining references to the wrong tag.

**Comment by nick-stroud** [comment]
Wow, that has bit me twice now. Thanks for the catch.

**Pull request merged**
